### ISSUE TITLE
Using sharp outside of Nuxt Image

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt/image#1093]
The sharp integration does not properly work if you use sharp outside of Nuxt Image.
The moment Nuxt throws any error sharp with also fail and you have to restart the dev environment.
If no other runtime error is thrown sharp works fine, as usual.

```
Something went wrong installing the "sharp" module

Module did not self-register: '/…/node_modules/sharp/build/Release/sharp-darwin-x64.node'.

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install

  Something went wrong installing the "sharp" module
  
  Module did not self-register: 'node_modules/sharp/build/Release/sharp-darwin-x64.node'.
  
  Possible solutions:
  - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
  - Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
  - Consult the installation documentation: https://sharp.pixelplumbing.com/install
  at Object.<anonymous> (node_modules/sharp/lib/sharp.js:37:9)
  at Module._compile (node:internal/modules/cjs/loader:1254:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
  at Module.load (node:internal/modules/cjs/loader:1117:32)
  at Module._load (node:internal/modules/cjs/loader:958:12)
  at Module.require (node:internal/modules/cjs/loader:1141:19)
  at require (node:internal/modules/cjs/helpers:110:18)
  at Object.<anonymous> (node_modules/sharp/lib/constructor.js:11:1)
  at Module._compile (node:internal/modules/cjs/loader:1254:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
```

package.json
```
"dependencies": {
  "@nuxt/image": "^1.0.0",
  "sharp": "^0.32.6"
}
```

**Comment by csnan** [comment]
I use the Windows environment npm run build, and the Mac environment. output/server/index.mjs, which also causes the same error.

windows sharp package: 
![0d6392556772fafa8b47caa26297e48f](https://github.com/nuxt/image/assets/47582074/78140c59-268d-47b8-8d99-909982494c06)

mac sharp package: 
![d768ca72c9296ef8e021f97347376ff8](https://github.com/nuxt/image/assets/47582074/47c76f6f-2c9a-4f92-bd4c-462dbf598f66)

node v18.13.0

**Comment by Baroshem** [comment]
Closing as this is a rather old issue.

Feel free to reopen if needed :)

**Comment by csnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
