### ISSUE TITLE
404 if images extension are uppercase

### ISSUE THREAD

**Issue by highlabs** [nuxt/image#1142]
Hi folks!

I was having problems after I migrated my website from nuxt-content 2 to 3. I tried multiple ways to fix the problem based on multiple issues that I found on this repo, but none worked.

After trying multiple ways to fix it, I found that the images cannot be uppercase.

Here are some examples of my `npm run generate` output:

Not working:
```
  │ ├── Error: [404] Document not found!
  │ └── Linked from /fotos/P1120698.JPG
  ├─ /api/_content/query/Gn8PDz2rQg.1701874912788.json (28ms)                                                                            nitro 3:02:00 pm
  │ ├── Error: [404] Document not found!
  │ └── Linked from /fotos/P1120744.JPG
  ├─ /api/_content/query/MZXqOD4oQD.1701874912788.json (28ms)                                                                            nitro 3:02:00 pm
  │ ├── Error: [404] Document not found!
  │ └── Linked from /fotos/P1120723.JPG
  ├─ /api/_content/query/hAFEqG1TWj.1701874912788.json (29ms)                                                                            nitro 3:02:00 pm
  │ ├── Error: [404] Document not found!
  │ └── Linked from /fotos/P1130030.JPG
  ├─ /api/_content/query/VItnWnoIqQ.1701874912788.json (28ms)                                                                            nitro 3:02:00 pm
  │ ├── Error: [404] Document not found!
  │ └── Linked from /fotos/P1130031.JPG
  ├─ /api/_content/query/4eLt3VaPYe.1701874912788.json (28ms)                                                                            nitro 3:02:00 pm
  │ ├── Error: [404] Document not found!
  │ └── Linked from /fotos/P1130019.JPG
                                                                                                                                         nitro 3:02:00 pm

 ERROR  Exiting due to prerender errors.                                                                                                       3:02:00 pm

  at prerender (node_modules/nitropack/dist/shared/nitro.0a84349b.mjs:216:11)
  at async node_modules/nuxt/dist/index.mjs:2992:7
  at async build (node_modules/nuxt/dist/index.mjs:4389:5)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:98:5)
  at async Object.run (node_modules/nuxi/dist/chunks/generate.mjs:59:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7) 

 ERROR  Exiting due to prerender errors.                                                                                                       3:02:00 pm
```

Working:

```
  ├─ /_ipx/fit_cover&s_448x448/fotos/P1120926.jpg (249ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_896x896/fotos/P1120926.jpg (250ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_448x448/fotos/P1120933.jpg (266ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_448x448/fotos/P1120937.jpg (267ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_896x896/fotos/P1120933.jpg (268ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_896x896/fotos/P1120937.jpg (268ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_896x896/fotos/P1120953.jpg (289ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_448x448/fotos/P1120963.jpg (289ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_896x896/fotos/P1120963.jpg (290ms)                           nitro 3:03:31 pm
  ├─ /_ipx/fit_cover&s_448x448/fotos/P1120953.jpg (290ms)                           nitro 3:03:31 pm
✔ Generated public .output/public                                                  nitro 3:03:31 pm
✔ You can preview this build using npx serve .output/public                        nitro 3:03:31 pm
✔ You can now deploy .output/public to any static hosting!  
```

And this is an example of what happens if I use only one image with uppercase extension: https://pastebin.com/RvWjf46f

This is an example of my .md files:

```
---
title: post title
tags:
  - tag
featured: 
    image: '/fotos/P1120954.jpg'
    alt: ''
photos:
  - image: '/fotos/P1120954.jpg'
    alt: ''
---

Post content
```

This is my nuxt.config.ts file:

```
import tailwindTypography from '@tailwindcss/typography'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxt/content', "@nuxt/image", "@nuxtjs/tailwindcss"],
  css: [
    '@/assets/css/global.css'
  ],
  tailwindcss: {
    config: {
      theme: {
        extend: {
          fontFamily: {
            sans: ["'Fira Code'", 'sans-serif']
          },
          container: {
            padding: '1rem',
            center: true,
          }
        }
      },
      plugins: [tailwindTypography]
    }
  }
})
```

this is my package.json:

```
{
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxt/content": "^2.9.0",
    "@nuxt/image": "^1.1.0",
    "@nuxtjs/tailwindcss": "^6.10.1",
    "@tailwindcss/typography": "^0.5.10",
    "nuxt": "^3.8.2"
  }
}
```

My machine:
Using Linux Pop-os and zsh.

**Comment by Baroshem** [comment]
Hey there,

I will close this issue as not planned. This is quite an edge case and there was no traffic on this issue.
