### ISSUE TITLE
socket hang up & connect ECONNREFUSED

### ISSUE THREAD

**Issue by angelorc** [nuxt/image#1158]
Hello everyone,

I've recently started experimenting with `nuxt/image`, but I am encountering some perplexing connection errors. Here's a brief overview of the issues:

```
ℹ Vite client warmed up in 669ms                                                                                                                                               11:57:25
ℹ Vite server warmed up in 6331ms                                                                                                                                              11:57:31
✔ Nitro built in 1019 ms                                                                                                                                                 nitro 11:57:31
mremap_chunk(): invalid pointer

 ERROR  [unhandledRejection] socket hang up                                                                                                                                     11:57:33

  at connResetException (node:internal/errors:720:14)
  at Socket.socketOnEnd (node:_http_client:519:23)
  at Socket.emit (node:events:526:35)
  at endReadableNT (node:internal/streams/readable:1376:12)
  at process.processTicksAndRejections (node:internal/process/task_queues:82:21)


 ERROR  [unhandledRejection] connect ECONNREFUSED 127.0.0.1:40005                                                                                                               11:57:49

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)

^C ELIFECYCLE  Command failed.
```

**Versions:**
- `@nuxt/image v1.1.0`
- `node v21.4.0` (also tested with `node v20.5.1`)

**Configuration**
```
image: {
    domains: ['raw.githubusercontent.com'],
}
```

Attempted URLs:
- http://127.0.0.1:3000/_ipx/h_200/https://raw.githubusercontent.com/bitsongofficial/assetlists/main/logos/adam.jpeg
- http://localhost:3000/_ipx/h_200/https://raw.githubusercontent.com/bitsongofficial/assetlists/main/logos/adam.jpeg

Has anyone experienced a similar error, or have any insights on what might be causing these connection issues?

**Comment by leo91000** [comment]
I have the same problem on a fresh manjaro linux computer. Do you have solved the issue @angelorc ?

**Comment by angelorc** [comment]
nope! still in my todo list

**Comment by leo91000** [comment]
> nope! still in my todo list

I think forcing the version of sharp to 0.32.6 fixed the issue for me :

```json
  "pnpm": {
    "overrides": {
      "sharp": "0.32.6"
    }
  }
```

Does it works for you too ?

**Comment by angelorc** [comment]
I finally had the chance to try your suggestion, and indeed, it resolves the socket hang-up bug. However, a new error has emerged:

```
 ERROR  [worker reload] [worker init]                                                                                                                                         12:17:18
Something went wrong installing the "sharp" module

Module did not self-register: '/home/angelo/Progetti/BitSong/bstudio/studio/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/build/Release/sharp-linux-x64.node'.

Possible solutions:
- Using worker threads? See https://sharp.pixelplumbing.com/install#worker-threads
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install

  Something went wrong installing the "sharp" module
  
  Module did not self-register: 'node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/build/Release/sharp-linux-x64.node'.
  
  Possible solutions:
  - Using worker threads? See https://sharp.pixelplumbing.com/install#worker-threads
  - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
  - Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
  - Consult the installation documentation: https://sharp.pixelplumbing.com/install
  at Object.<anonymous> (node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/sharp.js:37:9)
  at Module._compile (node:internal/modules/cjs/loader:1376:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
  at Module.load (node:internal/modules/cjs/loader:1207:32)
  at Module._load (node:internal/modules/cjs/loader:1023:12)
  at Module.require (node:internal/modules/cjs/loader:1235:19)
  at require (node:internal/modules/helpers:176:18)
  at Object.<anonymous> (node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/constructor.js:11:1)
  at Module._compile (node:internal/modules/cjs/loader:1376:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```
