### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by VegasChickiChicki** [nuxt/image#1315]
When i start vitest on nuxt project i see this:

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/@nuxt/image/dist/module.mjs:209:14
    at Array.map (<anonymous>)
    at setup (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/@nuxt/image/dist/module.mjs:208:39)
    at normalizedModule (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/@nuxt/kit/dist/index.mjs:2112:37)
    at async installModule (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
    at async initNuxt (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/nuxt/dist/index.mjs:4171:7)
    at async loadNuxt (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/nuxt/dist/index.mjs:4269:5)
    at async loadNuxt (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/@nuxt/kit/dist/index.mjs:2570:19)
    at async startNuxtAndGetViteConfig (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/@nuxt/test-utils/dist/config.mjs:40:16)
    at async getVitestConfigFromNuxt (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/@nuxt/test-utils/dist/config.mjs:83:15)
    at async file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/@nuxt/test-utils/dist/config.mjs:198:7
    at async loadConfigFromFile (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:68530:24)
    at async resolveConfig (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:68138:28)
    at async _createServer (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:64655:20)
    at async createViteServer (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:10951:18)
    at async createVitest (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:12219:18)
    at async startVitest (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:18772:15)
    at async start (file:///C:/Users/dodaa/WebstormProjects/site2/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:19563:17)
```

**Comment by Kheuval** [comment]
Hello, I'm having the same issue.

**My environment :**
nuxt@3.11.2
@nuxt/image@1.2.0

**Comment by Kheuval** [comment]
Hmm seems like I should have dig deeper ^^

The problem for me was that the `image.domains` in my `nuxt.config.ts` was set to an env variable and I didn't run the `vitest run` command with env variables.

@VegasChickiChicki maybe its the same for you ?

**Comment by VegasChickiChicki** [comment]
> Hmm seems like I should have dig deeper ^^
> 
> The problem for me was that the `image.domains` in my `nuxt.config.ts` was set to an env variable and I didn't run the `vitest run` command with env variables.
> 
> @VegasChickiChicki maybe its the same for you ?

This is help me, thanks!

**Comment by dukhevych** [comment]
in my case it failed here
```if (!d.startsWith("http")) {```

happens when domain is specified from variable that is undefined (for example env variable that doesn't exist)

probably it should throw some meaningful error in such cases
