### ISSUE TITLE
Can't generate static pages 

### ISSUE THREAD

**Issue by lumos94** [nuxt/image#1404]
when I am trying to generate a static page I get the below errors and the process stops.

`ENOENT: no such file or directory, mkdir 'C:\laragon\www\folder\project_folder\.output\public\_ipx\s_104x106\https:\cms.com\uploads' `
```
Errors prerendering:
  ├─ /_ipx/f_webp/https://cms.com/uploads/section1_image_86ade131d3.png (944ms)                                                                                                                                                                                                     nitro 4:19:24 pm  
  │ ├── Error: [500]
  │ └── Linked from /en/sala-de-trading
  │ └── Linked from /sala-de-trading
  ├─ /_ipx/f_webp&s_352x66/https://cms.com/uploads/dotted_arrows_down_icon_d5eaeb41e9.png (2042ms)     
```
my config is:
```
image: {
        format: ['webp', 'avif', 'png', 'jpeg', 'jpg', 'svg'],
        domains: [`${process.env.NUXT_STRAPI_URL}`, `${process.env.NUXT_BASE_URL}`],
        strapi: {
            baseURL: 'https://cms.com'
        }
    },
```

**Comment by Baroshem** [comment]
Could you provide a reproduction?

**Comment by trongtindev** [comment]
> Could you provide a reproduction?

Vercel or StackBlitz is no problem, only when building on Windows Local

```
ERROR  ENOENT: no such file or directory, mkdir 'D:\Github\nuxtui3\.output\public\_ipx\s_640x320\https:\i.imgur.com'
at async Object.mkdir (node:internal/fs/promises:858:10)
at async writeFile (/D:/Github/nuxtui3/node_modules/nitropack/dist/kit/index.mjs:53:3)
at async generateRoute (/D:/Github/nuxtui3/node_modules/nitropack/dist/core/index.mjs:2010:7)
...
at async Object.run (/D:/Github/nuxtui3/node_modules/nuxi/dist/chunks/build.mjs:104:5)
```

Reproduction link: [https://github.com/trongtindev/nuxt-image-error](https://github.com/trongtindev/nuxt-image-error)

**Comment by Baroshem** [comment]
I see. I dint have a Windows machine to test it on it unfortunately. 

Maybe someone from the community will be able to test this out and help.

**Comment by codeflorist** [comment]
This doesn't need a reproduction, as the source of the problem is clear:

Windows cannot create the file `C:\laragon\www\folder\project_folder\.output\public\_ipx\s_104x106\https:\cms.com\uploads`, since it has a colon from `https:` in it's path, and - contrary to Linux  - colons are not allowed in folder or file-names on windows.

Fixing this problem might be a bit problematic, since IPX expects the URL in this format, and the static file has to be created exactly as the URL for the webserver to deliver it.

One possible way would be for IPX to allow for base64 encoded baseURLs. But the filename itself (and maybe folders) should not be encoded.

So Instead of `/_ipx/f_webp/https://cms.com/uploads/image.png`, the src (and thus also the static filepath) could be something like `/_ipx/f_webp/aHR0cHM6Ly9jbXMuY29t/uploads/image.png`, which IPX decodes to actually fetch the image.

Another (maybe cleaner) solution would be to allow mapping of a baseURL to an "alias" in the config. E.g. like:
```js
image: {
  externalAlias: {
    cms: 'https://cms.com'
  }
}
```

So one could use `/_ipx/f_webp/cms/uploads/image.png` as the `src` (and static filepath), and IPX would resolve this to `/_ipx/f_webp/https://cms.com/uploads/image.png` to fetch the actual image.

This solution would not only fix the Windows problem, but also create nicer URLs and effectively hide the source-URL from the user - which can also be an advantage, as maybe one doesn't really want to disclose the CMS/API URL to the user in a statically generated site.

**Comment by codeflorist** [comment]
... turns out, there is already an `alias` option in NuxtImage: 😄
https://image.nuxt.com/get-started/configuration#alias

And it works great!

So @lumos94, you should be able to resolve your issue by putting this in your nuxt-config:
```js
image: {
	alias: {
		cms: 'https://cms.com'
	},
}
```

And then using e.g. `src="/cms/uploads/section1_image_86ade131d3.png"` as the `src` for `NuxtPicture`.
