### ISSUE TITLE
v1.8 breaks prerender

### ISSUE THREAD

**Issue by nandi95** [nuxt/image#1591]
After going from 1.7.0 to 1.8.0 the prerender now fails.
`Error:  [nuxt] [request error] [unhandled] [500] [nuxt] instance unavailable`
here are the relevant logs
```
  at useNuxtApp (./.nuxt/prerender/chunks/build/server.mjs:258:13)  
  at useRequestEvent (./.nuxt/prerender/chunks/build/server.mjs:796:36)  
  at prerenderStaticImages (./.nuxt/prerender/chunks/build/_base-CAUaGNyQ.mjs:22:16)  
  at getImage2 (./.nuxt/prerender/chunks/build/_base-CAUaGNyQ.mjs:137:7)  
  at Object.$img (./.nuxt/prerender/chunks/build/_base-CAUaGNyQ.mjs:142:12)  
  at getVariantSrc (./.nuxt/prerender/chunks/build/_base-CAUaGNyQ.mjs:308:14)  
  at getSizes (./.nuxt/prerender/chunks/build/_base-CAUaGNyQ.mjs:249:16)  
  at $img.getSizes (./.nuxt/prerender/chunks/build/_base-CAUaGNyQ.mjs:153:39)  
  at ./.nuxt/prerender/chunks/build/NuxtPicture-BHuUH0dC.mjs:45:45
```

And the relevant code snippet:
```
<NuxtLink v-for="category in categories"
          v-once
          :key="category.type"
          :to="{ name: 'products', query: { type: category.type } }"
          class="group relative">
    <NuxtPicture :src="category.image"
                 loading="lazy"
                 height="500"
                 preload
                 :alt="`${category.title} category`"
                 width="1000"
                 :img-attrs="{ class: 'rounded-lg' }" />
```

**Comment by ConnorMcF** [comment]
I've also just run into this when I added `preload` onto NuxtPicture.

**Comment by Baroshem** [comment]
Hey @nandi95 

Thanks for reporting this issue. Would you be able to create a reproduction repository/link with this issue? I can take a look at it :)
