### ISSUE TITLE
_ipx routes 500 on CentOS

### ISSUE THREAD

**Issue by a1mersnow** [nuxt/image#1651]
`nuxt generate` works well on MacOS and Windows machines but fails on CentOS machines.  
I cannot find out the reason because there are no clues.

```
...
[nitro]   ├─ /_ipx/s_2048x648/images/news/camera.png (24ms)
  │ ├── [500]
  │ └── Linked from /news/company-dynamic
  │ └── Linked from /news/industry-information
  │ └── Linked from /news/party-building
[nitro]   ├─ /_ipx/s_1280x405/images/news/camera.png (24ms)
  │ ├── [500]
  │ └── Linked from /news/company-dynamic
  │ └── Linked from /news/industry-information
  │ └── Linked from /news/party-building
[nitro]   ├─ /_ipx/s_1024x324/images/news/camera.png (28ms)
  │ ├── [500]
  │ └── Linked from /news/company-dynamic
  │ └── Linked from /news/industry-information
  │ └── Linked from /news/party-building
[nitro]   ├─ /_ipx/s_2560x810/images/news/camera.png (26ms)
  │ ├── [500]
  │ └── Linked from /news/company-dynamic
  │ └── Linked from /news/industry-information
  │ └── Linked from /news/party-building
[nitro]

 ERROR  Exiting due to prerender errors.

    at prerender (node_modules/.pnpm/nitropack@2.10.4_typescript@5.7.2/node_modules/nitropack/dist/core/index.mjs:2054:11)
    at async node_modules/.pnpm/nuxt@3.15.0_@parcel+watcher@2.5.0_@types+node@22.10.2_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_jqbpx2pqg4noffkjt76fdeyxvm/node_modules/nuxt/dist/index.mjs:4212:5
    at async build (node_modules/.pnpm/nuxt@3.15.0_@parcel+watcher@2.5.0_@types+node@22.10.2_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_jqbpx2pqg4noffkjt76fdeyxvm/node_modules/nuxt/dist/index.mjs:6572:3)
    at async Object.run (node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/chunks/build.mjs:103:5)
    at async Object.run (node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/chunks/generate.mjs:59:5)
    at async runCommand$1 (node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:1767:16)
    at async runCommand$1 (node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:1758:11)
    at async runMain$1 (node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:1896:7)



 ERROR  Exiting due to prerender errors.
```

**Comment by a1mersnow** [comment]
I investigate into the code and find:
```
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /var/lib/jenkins/workspace/bm-ui-www__staging/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/sharp.js
- /var/lib/jenkins/workspace/bm-ui-www__staging/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/constructor.js
- /var/lib/jenkins/workspace/bm-ui-www__staging/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install

    Something went wrong installing the "sharp" module

    Cannot find module '../build/Release/sharp-linux-x64.node'
    Require stack:
    - node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/sharp.js
    - node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/constructor.js
    - node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/index.js

    Possible solutions:
    - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
    - Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
    - Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at node:internal/modules/cjs/loader:1708:10
    at transformer (node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/register-C3TE0KFF.mjs:2:748)
    at Object.transformer (node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/register-C3TE0KFF.mjs:2:748)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
```

**Comment by a1mersnow** [comment]
```
sharp_binary_host=https://npmmirror.com/mirrors/sharp
sharp_libvips_binary_host=https://npmmirror.com/mirrors/sharp-libvips
```

I'm using `pnpm`, setting this in a `.npmrc` fixes my issue.
