### ISSUE TITLE
Customer Provider in nuxt.config.ts leads to: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by lowbits** [nuxt/image#175]
Hello, so im trying to add a custom provider in my nuxt.config.ts

``image: {
    providers: {
      customProvider: {
        name: 'customProvider',
        provider: './providers/myStaticProvider.ts',
      },
    },
  },``
  
  But when i run ``yarn nuxt-ts``
  
i get following error message

```

yarn run v1.22.10
$ nuxt-ts

 FATAL  The "path" argument must be of type string. Received undefined                                                                    13:10:59

  at new NodeError (node:internal/errors:329:5)
  at validateString (node:internal/validators:129:11)
  at Proxy.normalize (node:path:1045:5)
  at Object.normalize (/Users/tobi/git/monorepo-nuxt-app-typescript-tailwind-composition-api-boilerplate/node_modules/upath/build/code/upath.js:51:33)
  at resolveProvider (/Users/tobi/git/monorepo-nuxt-app-typescript-tailwind-composition-api-boilerplate/node_modules/@nuxt/image/dist/module.js:293:20)
  at resolveProviders (/Users/tobi/git/monorepo-nuxt-app-typescript-tailwind-composition-api-boilerplate/node_modules/@nuxt/image/dist/module.js:276:20)
  at ModuleContainer.imageModule (/Users/tobi/git/monorepo-nuxt-app-typescript-tailwind-composition-api-boilerplate/node_modules/@nuxt/image/dist/module.js:353:27)
  at ModuleContainer.addModule (/Users/tobi/git/monorepo-nuxt-app-typescript-tailwind-composition-api-boilerplate/node_modules/@nuxt/core/dist/core.js:235:34)
  at /Users/tobi/git/monorepo-nuxt-app-typescript-tailwind-composition-api-boilerplate/node_modules/@nuxt/utils/dist/utils.js:1859:43
  at ModuleContainer.ready (/Users/tobi/git/monorepo-nuxt-app-typescript-tailwind-composition-api-boilerplate/node_modules/@nuxt/core/dist/core.js:51:7)


   ╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                      │
   │   ✖ Nuxt Fatal Error                                                                                 │
   │                                                                                                      │
   │   TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined   │
   │                                                                                                      │
   ╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.


```

**Comment by sebastianhoitz** [comment]
This is fixed by 930e192f99a5bf2b00c7fb66316d67a062d81417

**Comment by sebastianhoitz** [comment]
However, it is not released yet. Could you publish a new version of nuxt/image?

**Comment by pi0** [comment]
Hi @sebastianhoitz sure. I'm finishing ipx rewrite. Publish is expected after migrate to ipx v1 :)
