### ISSUE TITLE
Use nuxt/image with dynamic url

### ISSUE THREAD

**Issue by ms-fadaei** [nuxt/image#196]
Hi and thanks for developing such an amazing module

I use NUXT/image with dynamic URLs that come with API requests.
In dev mode, there is no problem and URL generate with IPX (and serve locally)
but when I build my project the image src doesn't change

How can I use the IPX Image generator with dynamic images in this module?

**Comment by ms-fadaei** [comment]
I also tried 
``` js
image: {
    provider: "IPX",
}
```

and get this error

> Unknown provider: ipx

**Comment by dpschen** [comment]
@ms-fadaei The default image provider is static which uses IPX under the hood, so there should be no need to activate it manually.

Regarding the dynamic url:
I'm not sure if the component currently supports a changing url (didn't check), but if it doesn't maybe you can work around by adding a key with the dynamic url to the component, like this:

```vue
<nuxt-img :key="dynamicUrl" :src="dynamicUrl" />
```

**Comment by ms-fadaei** [comment]
@dpschen I tried and nothing changed!

My Source Code:
```js
<NuxtImg
    :key="banner"
    :src="banner"
    class="header-banner"
    sizes="xs:100vw sm:100vw md:100vw lg:100vw xl:100vw xxl:100vw"
    quality="80"
  />
```

in development:
```html
<img src="/_ipx/https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg?w=1500&amp;q=80"
sizes="(max-width: 360px) 100vw, (max-width: 576px) 100vw, (max-width: 768px) 100vw, (max-width: 992px) 100vw, (max-width: 1200px) 100vw, 100vw"
srcset="/_ipx/https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg?w=360&amp;q=80 360w,
   /_ipx/https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg?w=576&amp;q=80 576w,
   /_ipx/https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg?w=768&amp;q=80 768w,
   /_ipx/https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg?w=992&amp;q=80 992w,
   /_ipx/https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg?w=1200&amp;q=80 1200w,
   /_ipx/https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg?w=1500&amp;q=80 1500w"
class="header-banner" data-v-304be167="" data-v-b7abcb4a="">
```

after build:
```html
<img 
src="https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg" 
sizes="(max-width: 360px) 100vw, (max-width: 576px) 100vw, (max-width: 768px) 100vw, (max-width: 992px) 100vw, (max-width: 1200px) 100vw, 100vw"
srcset="https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 360w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 576w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 768w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 992w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 1200w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 1500w"
class="header-banner" data-v-9ea72bee="" data-v-02e8a236="">
```

**Comment by pi0** [comment]
Hi @ms-fadaei sorry for lack of documentation. Image module is still in development. In latest version, we need to manually add ipx middleware for using ipx in production. (non static)

```js
// nuxt.config
{
  image: {
    provider: 'ipx',
    ipx: {}
  }, 
  serverMiddleware: {
    '/_ipx': '~/server/middleware/ipx.js'
  },
}
```

```js
// server/middleware/ipx.js
import { createIPX, createIPXMiddleware } from 'ipx';
const ipx = createIPX({});
const middleware = createIPXMiddleware(ipx);
export default createIPXMiddleware(ipx);
```

**Comment by ms-fadaei** [comment]
When creating the IPX middleware file this error are shown:

```
Compiled with 2 warnings                                                                                                    


 WARN  in ./node_modules/sharp/lib/libvips.js                                                                                     

Critical dependency: the request of a dependency is an expression                                                                 
                                                                                                                                   
 WARN  in ./node_modules/sharp/build/Release/sharp.node                                                                            

Module parse failed: Unexpected character '�' (1:2)                                                                               
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
                                                                                                                                   
 @ ./node_modules/sharp/lib/constructor.js 11:2-40
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./nuxt-dist/client.js
                                                                                                                                   
 ERROR  Failed to compile with 8 errors                                                                                           

These dependencies were not found:                                                                                                 f
                                                                                                                                 
* child_process in ./node_modules/detect-libc/lib/detect-libc.js, ./node_modules/sharp/lib/libvips.js                             
* fs in ./node_modules/detect-libc/lib/detect-libc.js, ./node_modules/etag/index.js and 4 others
```

**Comment by pi0** [comment]
- Is it happening in development or production?
- In case of production what is your deployment method?

**Comment by ms-fadaei** [comment]
@pi0 This happened to me in developing (unfortunately I didn't test on production mode yet but I can check it as soon as possible and share the result)

**Comment by ms-fadaei** [comment]
@pi0 I get the error in production too (universal mode)

```
WARNING in ./node_modules/sharp/lib/libvips.js 64:23-70
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 400:33-39
Can't import the named export 'decode' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 349:41-52
Can't import the named export 'hasProtocol' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 398:23-35
Can't import the named export 'normalizeURL' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 399:17-27
Can't import the named export 'parseQuery' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 398:14-22
Can't import the named export 'parseURL' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 58:35-43
Can't import the named export 'readFile' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 39:18-25
Can't import the named export 'resolve' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 41:19-26
Can't import the named export 'resolve' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 47:20-24
Can't import the named export 'stat' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/ipx/dist/index.mjs 400:13-32
Can't import the named export 'withoutLeadingSlash' from non EcmaScript module (only default export is available)
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\SaLeH\Desktop\achareh-nuxt\node_modules\detect-libc\lib'
 @ ./node_modules/detect-libc/lib/detect-libc.js 4:16-40
 @ ./node_modules/sharp/lib/platform.js
 @ ./node_modules/sharp/lib/libvips.js
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/sharp/lib/libvips.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\SaLeH\Desktop\achareh-nuxt\node_modules\sharp\lib'
 @ ./node_modules/sharp/lib/libvips.js 6:18-42
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\SaLeH\Desktop\achareh-nuxt\node_modules\detect-libc\lib'
 @ ./node_modules/detect-libc/lib/detect-libc.js 5:18-31
 @ ./node_modules/sharp/lib/platform.js
 @ ./node_modules/sharp/lib/libvips.js
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/etag/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\SaLeH\Desktop\achareh-nuxt\node_modules\etag'
 @ ./node_modules/etag/index.js 22:12-25
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/fs-extra/lib/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\SaLeH\Desktop\achareh-nuxt\node_modules\fs-extra\lib'
 @ ./node_modules/fs-extra/lib/index.js 22:11-24
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\SaLeH\Desktop\achareh-nuxt\node_modules\graceful-fs'
 @ ./node_modules/graceful-fs/graceful-fs.js 1:9-22
 @ ./node_modules/fs-extra/lib/output/index.js
 @ ./node_modules/fs-extra/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/jsonfile/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\SaLeH\Desktop\achareh-nuxt\node_modules\jsonfile'
 @ ./node_modules/jsonfile/index.js 5:8-21
 @ ./node_modules/fs-extra/lib/json/jsonfile.js
 @ ./node_modules/fs-extra/lib/json/index.js
 @ ./node_modules/fs-extra/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/sharp/lib/libvips.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\SaLeH\Desktop\achareh-nuxt\node_modules\sharp\lib'
 @ ./node_modules/sharp/lib/libvips.js 3:11-24
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

ERROR in ./node_modules/sharp/build/Release/sharp.node 1:2
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/sharp/lib/output.js 4:14-52
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/ipx/dist/index.mjs
 @ ./src/middleware/ipx.server.js
 @ ./nuxt-dist/middleware.js
 @ ./nuxt-dist/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./nuxt-dist/client.js

 FATAL  Nuxt build error                                                                                                                           

  at WebpackBundler.webpackCompile (node_modules\@nuxt\webpack\dist\webpack.js:2125:21)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:2074:5)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:5)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-build.js:110:7)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)
```

**Comment by pi0** [comment]
@ms-fadaei I think you are using `middleware` directory (which is wrong). You have to use `server/middleware/ipx.js` (or `api/ipx.js`)

**Comment by ms-fadaei** [comment]
@pi0 
Thank you.

know my project run without any error & warning. but...

my URL didn't change at all (in the static provider it's ok on dev and not working in production).

in both dev and production mode I get this:
```html
<img 
src="https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg" 
sizes="(max-width: 360px) 100vw, (max-width: 576px) 100vw, (max-width: 768px) 100vw, (max-width: 992px) 100vw, (max-width: 1200px) 100vw, 100vw"
srcset="https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 360w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 576w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 768w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 992w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 1200w,
   https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg 1500w"
class="header-banner" data-v-9ea72bee="" data-v-02e8a236="">
```

I tested the IPX URL too, but it has an error:
URL: `http://localhost:3020/_ipx/https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg`
The error: `Forbidden URL:https://cdn.aXXXXXXh.ir/production.aXXXXXXh.ir/delegates/landings/fc72d220-e257-486a-bf46-46b2ba4ea074/af355d2e-bd6c-47c4-9643-82b16099f288.jpg`

**Comment by ms-fadaei** [comment]
I figured out whats the problem (for remote domains)

In `server/middleware/ipx.js`, I must set the domains too:
```js
import {createIPX, createIPXMiddleware} from "ipx";

export default createIPXMiddleware(
  createIPX({
    domains: ["https://cdn.aXXXXXXh.ir"],
  })
);
```

in this case, my problem has been solved.
but there is a problem: I have an IPX option in image config in 'nuxt.config.js' as you mentioned:
```js
// nuxt.config
{
  image: {
    provider: 'ipx',
    ipx: {}
  }, 
  serverMiddleware: {
    '/_ipx': '~/server/middleware/ipx.js'
  },
}
```

if I set domains in the IPX config object in the Nuxt config file, my problem is still there and I must set the domains statically in `server/middleware/ipx.js`.
so I rewrite my `server/middleware/ipx.js` like this to support the `ipx` option
```js
import {createIPX, createIPXMiddleware} from "ipx";
import config from "../../../nuxt.config.js";

const {
  image: {ipx: ipxConfig},
} = config;

export default createIPXMiddleware(createIPX(ipxConfig));
```

**Comment by ms-fadaei** [comment]
@pi0 
well, I moved my project to the test server.

now I got an error with a 404 status code from IPX for my external image (witch that was ok on my localhost)

the message is:
`404 File not found: /home/devops/axxxxxhnuxtfront/https:/cdn.axxxxxh.ir/production.axxxxxh.ir/listings/services/0e5e5bee-2eae-45b9-8b38-afbaa5848bab/banner.jpg`

and the URL of my image is:
`ttps://nuxt.axxxxxh.ir/_ipx/https://cdn.axxxxxh.ir/production.axxxxxh.ir/listings/services/0e5e5bee-2eae-45b9-8b38-afbaa5848bab/banner.jpg?q=70&s=250_150`

the deferce is `/https://cdn.axxxxxh.ir` and `/https:/cdn.axxxxxh.ir` (two slash after https:)

I run my project in `Ubuntu 16.04.6 LTS` environment witch my localhost was in `windows 10`

Do you have any idea what's going on???

**Comment by thomas4Bitcraft** [comment]
I have the same problem. If I use the library in dev mode everything is fine. If I use it in production ( even with the server middleware ) the urls don't get rewritten

**Comment by urbgimtam** [comment]
I'm suffering of the exact same issue (image generated is writing 'https:/domain' instead of 'https://domain').
I'm using the latest version. Any reason why the regression?

**Comment by urbgimtam** [comment]
I've managed to 'solve' it in production by using an ['alias'](https://image.nuxtjs.org/api/options#alias) . But why can't I use the regular domains?

**Comment by imaxsof** [comment]
@urbgimtam please attach an example of how you solved this with `alias`?

**Comment by urbgimtam** [comment]
@imaxsof Sure.

On nuxt.config.js:
`
image: {
  // permitted domains where the files are stored
  domains: ['sub.domain.here', 'another.domain.here'], 

  // define alias(es) that will replace the domains above
  alias: {
    imgs: 'https://sub.domain.here',
    anotherimgs: 'https://another.domain.here'
  },

  dir: 'static',
}
`

Then, inside a component:
`
<template>
  <nuxt-img :src="aliasedUrl (fullImagePath)" />
</template>
<script>
data() {
  return {
    fullImagePath: 'https://sub.domain.here/full_image/url.jpg'
  }
},

methods: {
  aliasedUrl (fullUrl) {
   // Replace the whole original domain with the alias
   // Final url to send to nuxt-image should be '/imgs/full_image/url.jpg'
    return fullUrl.replace('https://sub.domain.here', '/imgs' )
  }
}
</script>
`
