### ISSUE TITLE
ERROR: Request path contains unescaped characters

### ISSUE THREAD

**Issue by ateliershen** [nuxt/image#307]
Edit:

Use `encodeURI ` will solve this issue.

![image](https://user-images.githubusercontent.com/30176935/120407159-27bea300-c37f-11eb-8aaf-613e64a7879c.png)

========

Hi,

Thanks for building this module! 

I encountered this issue while testing on my site:

```
 ERROR  Request path contains unescaped characters 

  at new ClientRequest (_http_client.js:148:13)
  at request (https.js:314:10)
  at node_modules/node-fetch/lib/index.js:1438:17
  at new Promise (<anonymous>)
  at Object.fetch [as default] (node_modules/node-fetch/lib/index.js:1407:10)
  at Object.http (node_modules/ipx/dist/index.js:91:53)
  at node_modules/ipx/dist/index.js:370:33
  at Object.src (node_modules/ipx/dist/index.js:42:25)
  at handleRequest (node_modules/ipx/dist/index.js:429:25)
  at IPXMiddleware (node_modules/ipx/dist/index.js:456:5)
  at call (node_modules/connect/index.js:239:7)
  at next (node_modules/connect/index.js:183:5)
  at next (node_modules/connect/index.js:161:14)
  at next (node_modules/connect/index.js:161:14)
  at WebpackBundler.middleware (node_modules/@nuxt/webpack/dist/webpack.js:2194:5)
```

This happens when the remote URL contains non-alphanumeric characters (in my case there are Chinese characters in the filenames). But I am not able to rename the remote image filenames. Is there any workaround for this? Thanks!

**Comment by ateliershen** [comment]
Thanks for the reply! This is one example of the file URL:

![image](https://user-images.githubusercontent.com/30176935/120406725-1cb74300-c37e-11eb-9f15-5b9196a7cd34.png)

Link (Github transcoded the characters directly)
https://sbf.sph.pm/wp-content/uploads/2021/05/%E6%9D%8E%E7%BE%8E%E8%8A%B1-Lee-Bee-Wah.jpg

**Comment by danielroe** [comment]
I believe this is resolved in the latest version of the module (https://github.com/nuxt/image/commit/852371a6305903f6c18c07483f9cb494d5f99c63). Please do let me know if not and we can investigate further.
