### ISSUE TITLE
Vercel build error

### ISSUE THREAD

**Issue by strebl** [nuxt/image#344]
Hi guys 👋🏻 

Should it be possible to use `nuxt-image` on Vercel with a different provider, for example Cloudinary?

I get build errors on Vercel:
```
20:01:53.279    |    error    /vercel/path0/node_modules/sharp: Command failed.
```

As far as I know, that has something to do with IPX. I'm aware of #141 but I think that's a different problem. I don't want IPX on Vercel.

Here my nuxt configuration:

```js
// nuxt.config.js
export default {
  head: {
    title: 'nuxt-image-test',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  css: [],

  plugins: [],

  components: true,

  buildModules: [
    '@nuxtjs/eslint-module',
    '@nuxtjs/tailwindcss',
  ],

  modules: [
    '@nuxtjs/axios',
    '@nuxt/image',
  ],

  axios: {},

  image: {
    provider: 'cloudinary',
    screens: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280,
      xxl: 1536,
      '2xl': 1900,
    },
    cloudinary: {
      baseURL: 'https://res.cloudinary.com/myorg/image/upload/',
    },
  },

  build: {},
}
```

I also tried it with `'@nuxt/image'` in buildModules and without custom `image` config at all.

Am I missing something?

Thanks for your help!

**Comment by pi0** [comment]
Hi @strebl. It seems you are not using either static or ipx providers at all so this error is strange. Would you please share a more detailed build error? And are you using [vercel-builder](https://github.com/nuxt/vercel-builder)?

**Comment by ririen** [comment]
@pi0  I encountered the same error. It is the latest version of `sharp` assigned to IPX package. Vercel does not support the latest `libvips`

@strebl if you are using `yarn` adding to the code below to package.json should solve the case :)

```json
    "resolutions": {
        "sharp": "0.27.0"
    }
  ```
  
  And `yarn install` of course.
  
  This code will make your project use the older `sharp` version that Vercel supports.

**Comment by strebl** [comment]
Hi @pi0. Yes, I'm using the vercel-builder. Here is the detailed log:

```


14:37:10.734 | Cloning github.com/nmbrz/nohe-web (Branch: features/performance, Commit: c3b6a4e)
-- | --
14:37:11.858 | Cloning completed: 1.124s
14:37:11.893 | Analyzing source code...
14:37:11.904 | Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
14:37:12.920 | Installing build runtime...
14:37:15.764 | Build runtime installed: 2.844s
14:37:18.259 | Looking up build cache...
14:37:18.347 | Build Cache not found
14:37:19.440 | Running with @nuxt/vercel-builder version 0.21.2
14:37:19.440 | ----------------- Prepare build -----------------
14:37:19.440 | Downloading files...
14:37:19.441 | Working directory: /vercel/path0
14:37:19.443 | Using yarn
14:37:19.445 | ℹ Prepare build took: 4.22576 ms
14:37:19.445 | ----------------- Install devDependencies -----------------
14:37:19.807 | yarn install v1.22.10
14:37:19.909 | [1/5] Resolving packages...
14:37:20.423 | [2/5] Fetching packages...
14:37:39.886 | info fsevents@2.3.2: The platform "linux" is incompatible with this module.
14:37:39.887 | info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
14:37:39.899 | info fsevents@1.2.13: The platform "linux" is incompatible with this module.
14:37:39.899 | info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
14:37:39.917 | [3/5] Linking dependencies...
14:37:39.917 | warning "nuxt > @nuxt/components@2.1.8" has unmet peer dependency "consola@*".
14:37:39.972 | warning "v-tooltip > vue-resize@1.0.1" has unmet peer dependency "vue@^2.6.0".
14:37:39.972 | warning " > vee-validate@3.4.8" has unmet peer dependency "vue@^2.5.18".
14:37:39.972 | warning " > vue-js-modal@2.0.0-rc.6" has unmet peer dependency "vue@2.6.11".
14:37:39.972 | warning " > vue-select@3.11.2" has unmet peer dependency "vue@2.x".
14:37:39.972 | warning "@nuxtjs/eslint-config > eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 \|\| >= 3.2.0-dev \|\| >= 3.3.0-dev \|\| >= 3.4.0-dev \|\| >= 3.5.0-dev \|\| >= 3.6.0-dev \|\| >= 3.6.0-beta \|\| >= 3.7.0-dev \|\| >= 3.7.0-beta".
14:37:39.972 | warning "@nuxtjs/eslint-module > eslint-webpack-plugin@2.5.4" has unmet peer dependency "webpack@^4.0.0 \|\| ^5.0.0".
14:37:39.972 | warning " > tailwindcss@2.1.2" has unmet peer dependency "autoprefixer@^10.0.2".
14:37:39.972 | warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > css-loader@5.2.6" has unmet peer dependency "webpack@^4.27.0 \|\| ^5.0.0".
14:37:39.972 | warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > postcss-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0 \|\| ^5.0.0".
14:37:39.972 | warning "@teamnovu/nuxt-breaky > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 \|\| ^5.0.0".
14:37:39.972 | warning "@teamnovu/nuxt-breaky > @nuxtjs/tailwindcss > nuxt-purgecss > purgecss-webpack-plugin@1.6.0" has unmet peer dependency "webpack@^4 \|\| ^3".
14:37:39.973 | warning " > sass-loader@10.2.0" has unmet peer dependency "webpack@^4.36.0 \|\| ^5.0.0".
14:37:59.323 | [4/5] Building fresh packages...
14:38:03.280 | error /vercel/path0/node_modules/sharp: Command failed.
14:38:03.280 | Exit code: 1
14:38:03.280 | Command: (node install/libvips && node install/dll-copy && prebuild-install) \|\| (node install/can-compile && node-gyp rebuild && node install/dll-copy)
14:38:03.280 | Arguments:
14:38:03.281 | Directory: /vercel/path0/node_modules/sharp
14:38:03.281 | Output:
14:38:03.281 | sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-linux-x64.tar.br
14:38:03.281 | /bin/sh: prebuild-install: command not found
14:38:03.281 | gyp info it worked if it ends with ok
14:38:03.281 | gyp info using node-gyp@5.1.0
14:38:03.281 | gyp info using node@14.16.1 \| linux \| x64
14:38:03.281 | gyp info find Python using Python version 2.7.18 found at "/usr/bin/python"
14:38:03.281 | gyp http GET https://nodejs.org/download/release/v14.16.1/node-v14.16.1-headers.tar.gz
14:38:03.281 | gyp http 200 https://nodejs.org/download/release/v14.16.1/node-v14.16.1-headers.tar.gz
14:38:03.281 | gyp http GET https://nodejs.org/download/release/v14.16.1/SHASUMS256.txt
14:38:03.281 | gyp http 200 https://nodejs.org/download/release/v14.16.1/SHASUMS256.txt
14:38:03.281 | gyp info spawn /usr/bin/python
14:38:03.281 | gyp info spawn args [
14:38:03.281 | gyp info spawn args   '/node14/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
14:38:03.281 | gyp info spawn args   'binding.gyp',
14:38:03.281 | gyp info spawn args   '-f',
14:38:03.281 | gyp info spawn args   'make',
14:38:03.281 | gyp info spawn args   '-I',
14:38:03.281 | gyp info spawn args   '/vercel/path0/node_modules_dev/sharp/build/config.gypi',
14:38:03.281 | gyp info spawn args   '-I',
14:38:03.281 | gyp info spawn args   '/node14/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
14:38:03.281 | gyp info spawn args   '-I',
14:38:03.281 | gyp info spawn args   '/vercel/.cache/node-gyp/14.16.1/include/node/common.gypi',
14:38:03.281 | gyp info spawn args   '-Dlibrary=shared_library',
14:38:03.281 | gyp info spawn args   '-Dvisibility=default',
14:38:03.281 | gyp info spawn args   '-Dnode_root_dir=/vercel/.cache/node-gyp/14.16.1',
14:38:03.282 | gyp info spawn args   '-Dnode_gyp_dir=/node14/lib/node_modules/npm/node_modules/node-gyp',
14:38:03.282 | gyp info spawn args   '-Dnode_lib_file=/vercel/.cache/node-gyp/14.16.1/<(target_arch)/node.lib',
14:38:03.282 | gyp info spawn args   '-Dmodule_root_dir=/vercel/path0/node_modules_dev/sharp',
14:38:03.282 | gyp info spawn args   '-Dnode_engine=v8',
14:38:03.282 | gyp info spawn args   '--depth=.',
14:38:03.282 | gyp info spawn args   '--no-parallel',
14:38:03.282 | gyp info spawn args   '--generator-output',
14:38:03.282 | gyp info spawn args   'build',
14:38:03.282 | gyp info spawn args   '-Goutput_dir=.'
14:38:03.282 | gyp info spawn args ]
14:38:03.282 | gyp info spawn make
14:38:03.282 | gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
14:38:03.282 | make: Entering directory `/vercel/path0/node_modules_dev/sharp/build'
14:38:03.282 | CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
14:38:03.282 | AR(target) Release/obj.target/../node-addon-api/nothing.a
14:38:03.282 | COPY Release/nothing.a
14:38:03.282 | TOUCH Release/obj.target/libvips-cpp.stamp
14:38:03.282 | CXX(target) Release/obj.target/sharp/src/common.o
14:38:03.282 | ../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
14:38:03.282 | #include <vips/vips8>
14:38:03.282 | ^~~~~~~~~~~~
14:38:03.282 | compilation terminated.
14:38:03.282 | make: *** [Release/obj.target/sharp/src/common.o] Error 1
14:38:03.282 | make: Leaving directory `/vercel/path0/node_modules_dev/sharp/build'
14:38:03.282 | gyp ERR! build error
14:38:03.282 | gyp ERR! stack Error: `make` failed with exit code: 2
14:38:03.283 | gyp ERR! stack     at ChildProcess.onExit (/node14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
14:38:03.283 | gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
14:38:03.283 | gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
14:38:03.283 | gyp ERR! System Linux 4.14.225-168.357.amzn2.x86_64
14:38:03.283 | gyp ERR! command "/node14/bin/node" "/node14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
14:38:03.283 | gyp ERR! cwd /vercel/path0/node_modules_dev/sharp
14:38:03.283 | gyp ERR! node -v v14.16.1
14:38:03.283 | gyp ERR! node-gyp -v v5.1.0
14:38:03.283 | gyp ERR! not ok
14:38:03.283 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
14:38:03.322 | Error: Command "yarn install" exited with 1

```

**Comment by DKhalil** [comment]
> ```json
> "resolutions": {
>         "sharp": "0.27.0"
>     }
> ```

The resolution isn't taking since ipx is requiring ^0.28.3 for sharp.

**Comment by ririen** [comment]
Indeed, the` resolutions` will no longer work due to updates. I was able to get through the build correctly as follows:

Changing the vercel.json file to:
```json
{
  "version": 2,
  "builds": [
    {
      "src": "package.json",
      "use": "@vercel/node"
    },
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/vercel-builder"
    }
  ]
}
```

I added in `package.json` as dependencies: `"sharp": "latest"`

I have added a new script to package.json: `"vercel-build": "yarn global add prebuild-install"`

**Comment by pi0** [comment]
Can you please try with version > 0.6.x . IPX is now optional (#403)
