### ISSUE TITLE
Nuxt Fatal Error : Cannot find module '@nuxt/image' 

### ISSUE THREAD

**Issue by dosstx** [nuxt/image#433]
I have a universal NuxtJS2 app and am trying to use Nuxt Image module to handle my avatars like so:

`<NuxtImg :width="width" :height="height" :src="src" />` where the `src` has an image URL coming from `https://lh3.googleusercontent.com`. I have that domain whitelisted.

In my nuxt.config.js I have the module set up like so:

```
modules: ['@nuxt/image']`
image: {
 domains: ['https://lh3.googleusercontent.com']
```

Elsewhere in my app, I am using a third-party provider to handle some other imagery like so:

```
          <NuxtImg
            provider="cloudinary"
            :src="post.publicId"
            :width="post.width"
            :height="post.height"
            class="figure-img img-fluid card-img-top shadow"
            sizes="xs:510px sm:730px md:630px lg:755px xl:740px xxl:900px"
            :alt="post.title"
            :title="post.caption"
          />
```

This all works great locallly, but when I deploy to production (Heroku) , the deploy fails and I get the following log error:

```
WARN  Module @nuxt/image not found. Please ensure @nuxt/image is in dependencies and installed.
2021-10-05T11:47:45.162802+00:00 app[web.1]:
2021-10-05T11:47:45.163845+00:00 app[web.1]:
2021-10-05T11:47:45.163847+00:00 app[web.1]: FATAL  Cannot find module '@nuxt/image'
2021-10-05T11:47:45.163847+00:00 app[web.1]: Require stack:
2021-10-05T11:47:45.163847+00:00 app[web.1]: - /app/node_modules/@nuxt/core/dist/core.js
2021-10-05T11:47:45.163847+00:00 app[web.1]:
2021-10-05T11:47:45.163848+00:00 app[web.1]: Require stack:
2021-10-05T11:47:45.163848+00:00 app[web.1]: - node_modules/@nuxt/core/dist/core.js
2021-10-05T11:47:45.163849+00:00 app[web.1]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
2021-10-05T11:47:45.163849+00:00 app[web.1]: at Function.resolve (node:internal/modules/cjs/helpers:98:19)
2021-10-05T11:47:45.163850+00:00 app[web.1]: at p (node_modules/jiti/dist/jiti.js:1:52987)
2021-10-05T11:47:45.163850+00:00 app[web.1]: at Resolver.v [as _require] (node_modules/jiti/dist/jiti.js:1:53886)
2021-10-05T11:47:45.163850+00:00 app[web.1]: at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
2021-10-05T11:47:45.163851+00:00 app[web.1]: at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:182:38)
2021-10-05T11:47:45.163851+00:00 app[web.1]: at node_modules/@nuxt/utils/dist/utils.js:639:43
2021-10-05T11:47:45.163851+00:00 app[web.1]: at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
2021-10-05T11:47:45.163852+00:00 app[web.1]: at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
2021-10-05T11:47:45.163852+00:00 app[web.1]:
2021-10-05T11:47:45.167060+00:00 app[web.1]:
2021-10-05T11:47:45.167062+00:00 app[web.1]: ╭─────────────────────────────────────────────────╮
2021-10-05T11:47:45.167062+00:00 app[web.1]: │                                                 │
2021-10-05T11:47:45.167063+00:00 app[web.1]: │   ✖ Nuxt Fatal Error                            │
2021-10-05T11:47:45.167063+00:00 app[web.1]: │                                                 │
2021-10-05T11:47:45.167063+00:00 app[web.1]: │   Error: Cannot find module '@nuxt/image'       │
2021-10-05T11:47:45.167064+00:00 app[web.1]: │   Require stack:                                │
2021-10-05T11:47:45.167064+00:00 app[web.1]: │   - /app/node_modules/@nuxt/core/dist/core.js   │
2021-10-05T11:47:45.167064+00:00 app[web.1]: │                                                 │
2021-10-05T11:47:45.167065+00:00 app[web.1]: ╰─────────────────────────────────────────────────╯
2021-10-05T11:47:45.167065+00:00 app[web.1]:
2021-10-05T11:47:45.294025+00:00 heroku[web.1]: Process exited with status 1
```

Should I be placing the `@nuxt/image` module in my `dependencies` and NOT `devDependencies` of package.json? Please advise as I want to make sure I'm not adding unnecessary dependencies where they shouldn't be placed. Thanks!

**Comment by shadow81627** [comment]
> Add @nuxt/image devDependency to your project

https://image.nuxtjs.org/getting-started/installation

**Comment by dosstx** [comment]
> > Add @nuxt/image devDependency to your project
> 
> https://image.nuxtjs.org/getting-started/installation

So, should it be in BOTH devDep and Dep?
