### ISSUE TITLE
Doesn't work with nuxt3

### ISSUE THREAD

**Issue by Zielgestalt** [nuxt/image#439]
Fresh nuxt3 install

Mac OSX
Node: v14.17.6

yarn dev -o

`
Nuxt CLI v3.0.0-27235451.ece0e01                                                                                                                                                        15:07:37
                                                                                                                                                                                        15:07:37
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.86.38:3000/

 ERROR  Error compiling template:  {                                                                                                                                                    15:07:40
  fileName: 'image.js',
  src: '....../node_modules/@nuxt/image/dist/runtime/plugin.js',
  options: {
    imageOptions: {
      screens: [Object],
      presets: {},
      provider: 'ipx',
      domains: [],
      alias: {}
    },
    providers: [
      [Object],
      [Object]
    ]
  },
  filename: 'image.js',
  dst: '/....../.nuxt/image.js'
}

 ERROR  Cannot start nuxt:  options is not defined                                                                                                                                      15:07:40

  at eval (eval at <anonymous> (node_modules/lodash.template/index.js:1550:12), <anonymous>:8:10)
  at compileTemplate (node_modules/@nuxt/kit/dist/index.mjs:952:45)
  at async node_modules/nuxt3/dist/index.mjs:940:22
  at async Promise.all (index 8)
  at async generateApp (node_modules/nuxt3/dist/index.mjs:939:3)
  at async build (node_modules/nuxt3/dist/index.mjs:977:3)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6764:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6794:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:417:7)

✔ Generated nuxt.d.ts                                                                                                                                                                   15:07:40
`

**Comment by Zielgestalt** [comment]
Closing this as duplicate of https://github.com/nuxt/image/issues/453
