### ISSUE TITLE
Could not resolve "#imports" when using @nuxt/image-edge

### ISSUE THREAD

**Issue by jusjus112** [nuxt/image#647]
Got the following error when starting nuxt 3.
I am using 

- "@nuxt/image-edge": "^1.0.0-27769790.4b27db3"
- "nuxt": "npm:nuxt@3.0.0-rc.12"

It used to work fine, but once I upgraded to Nuxt rc.13 and then downgraded again, it gave the following error when starting a dev server.

I tried the following:

- Cleared my cache with NPM
- Cleared the cache from Nuxt
- Downgraded to use older image-edge versions from NPM

`X [ERROR] Could not resolve "#imports"

    node_modules/@nuxt/image-edge/dist/runtime/composables.mjs:1:27:
      1 │ import { useNuxtApp } from "#imports";
        ╵                            ~~~~~~~~~~

  You can mark the path "#imports" as external to exclude it from the bundle, which will remove this
  error.

 ERROR  8:28:47 PM [vite] error while updating dependencies:                                                                                                                                                                                               20:28:47  
Error: Build failed with 1 error:
node_modules/@nuxt/image-edge/dist/runtime/composables.mjs:1:27: ERROR: Could not resolve "#imports"
    at failureErrorWithLog (\node_modules\esbuild\lib\main.js:1566:15)
    at \node_modules\esbuild\lib\main.js:1024:28
    at runOnEndCallbacks (\node_modules\esbuild\lib\main.js:1438:61)
    at buildResponseToResult (\node_modules\esbuild\lib\main.js:1022:7)
    at \node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
`

**Comment by danielroe** [comment]
Would you try adding `/image-edge/` to you `build.transpile` array?

**Comment by jusjus112** [comment]
I currently have this.
Without success.

```
build: {
    transpile: [
        "/image-edge/"
    ],
    ...
  },
```

**Comment by danielroe** [comment]
Try removing the quotes.

**Comment by jusjus112** [comment]
> Try removing the quotes.

Hi thanks for your response, but I did that already. I even used conditionally transpile with Nuxt. So I am thinking the issue is somewhere else?

**Comment by danielroe** [comment]
In that case, would you provide a reproduction? 🙏

**Comment by jusjus112** [comment]
> In that case, would you provide a reproduction? 🙏

Here is the reproduction: https://stackblitz.com/edit/nuxt-starter-j8nfhg

**Comment by danielroe** [comment]
I'm looking for [a minimal reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction) - there's a lot going on in that sandbox.

**Comment by jusjus112** [comment]
Alright. I have made a minimal starter with current dependencies such as "sass & sass-loader" so the components won't break.

I have found a conflict with the "swiper" dependency.
Whenever I remove this dependency the error is gone, when I add it and use it keeps happening.
Of course, a solution is to remove this dependency, but it shouldn't technically interfere.

https://stackblitz.com/edit/nuxt-starter-dnhbmv

**Comment by danielroe** [comment]
`@nuxtjs/axios` does not support Nuxt 3 and will almost certainly be pulling in outdated dependencies. You're also still on an old rc of Nuxt 3. There are also some issues with what you're importing and how. But I can't really check as the repro won't run; I think it's missing some files - there's no assets directory, for example.

**Comment by jusjus112** [comment]
> `@nuxtjs/axios` does not support Nuxt 3 and will almost certainly be pulling in outdated dependencies. You're also still on an old rc of Nuxt 3. There are also some issues with what you're importing and how. But I can't really check as the repro won't run; I think it's missing some files - there's no assets directory, for example.

Hi, makes sense, but since some dependencies are not yet compatable with the stable version of nuxt 3 I am waiting to update. But I understand the repo won't run, thats the entire point of this github issue. Just ignore the missing assets and components, it's because the error at the bottom. The same error I posted in the first comment above. You asked to recreate the error, I did. Just ignore the axios dependency, as it will work. You can even remove it and it still will throw the #imports error.

**Comment by danielroe** [comment]
It does not throw that error once I clean up your reproduction to remove references to non-existent components and assets: https://stackblitz.com/edit/nuxt-starter-1mjykb.
