### ISSUE TITLE
Nuxt 3 error Cannot find module './runtime/providers/ipx'

### ISSUE THREAD

**Issue by maxleistner** [nuxt/image#679]
Hi, i got a nuxt v3 project and tried to get image-edge up and running. I installed the package `yarn add --dev @nuxt/image-edge` and added `modules: [
    '@nuxt/image-edge',
  ]` but after restarting the server i get the following error. What am i missing? 

```
 ERROR  Cannot restart nuxt:  Cannot find module './runtime/providers/ipx'                                                                                                                      15:54:30
Require stack:
- /Users/***/node_modules/@nuxt/image-edge/dist/module.mjs

  Require stack:
  - node_modules/@nuxt/image-edge/dist/module.mjs
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at resolveProvider (node_modules/@nuxt/image-edge/dist/module.mjs:108:72)
  at resolveProviders (node_modules/@nuxt/image-edge/dist/module.mjs:90:28)
  at setup (node_modules/@nuxt/image-edge/dist/module.mjs:177:29)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:29)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)                                                                                                                                  15:54:14
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6713:10)
  ```
  
  
  if i ad a custom provider i get
  ```
  [nuxt] [request error] [unhandled] [500] defineNuxtPlugin is not defined                                                                                                                        16:01:30
  at ./node_modules/@nuxt/image-edge/dist/runtime/plugin.mjs:5:1
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:270:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:146:12)
  at async request (./node_modules/vite-node/dist/client.mjs:169:16)
  at async virtual:nuxt:./.nuxt/plugins/server.mjs:7:31
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:270:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:146:12)
  at async request (./node_modules/vite-node/dist/client.mjs:169:16)
  at async ./node_modules/nuxt/dist/app/entry.mjs:11:31
  ```

**Comment by kiranimeid** [comment]
got the same issue today, did you manage to get it working?

**Comment by xhayper** [comment]
Are you using Yarn 3 by any chance?

**Comment by xhayper** [comment]
I figured it out for me, `yarn add --dev @nuxt/image-edge` would install `1.0.0-testing` instead of the latest version, causing the weird error.

To properly install it, you can install `yarn add --dev @nuxt/image-edge@1.0.0-27840416.dc1ed65` (latest beta build as of right now)

Don't forget to remove the `^` from the version in `package.json` too.

**Comment by Velka-DEV** [comment]
> I figured it out for me, `yarn add --dev @nuxt/image-edge` would install `1.0.0-testing` instead of the latest version, causing the weird error.
> 
> To properly install it, you can install `yarn add --dev @nuxt/image-edge@1.0.0-27840416.dc1ed65` (latest beta build as of right now)
> 
> Don't forget to remove the `^` from the version in `package.json` too.

This is not actually true, for me `yarn add --dev @nuxt/image-edge` install the correct last build (1.0.0-27840416.dc1ed65) but that don't solve the problem anyway.

**Comment by kuohuanhuan** [comment]
Removing the `^` prefix solves my problem, too.

(with Yarn Berry 3.3.1)

**Comment by pi0** [comment]
Since the issue is old, please ping to reopen with new production

**Comment by letavocado** [comment]
Hi, @pi0!

Still exist with
`"@nuxt/image-edge": "^1.0.0-28020728.5df24eb"`
`"packageManager": "yarn@3.5.0"`

If I remove the `^` as mentioned @xhayper then works.

Thanks!

**Comment by xhayper** [comment]
This issue is caused by the package manager, and not the package itself, the way yarn parse version range is wonky and it ended up installing `1.0.0-testing`

**Comment by letavocado** [comment]
Thanks @xhayper!

**Comment by JPustkuchen** [comment]
Use `@nuxt/image` instead. See updated documentation: https://v1.image.nuxtjs.org/get-started

This resolves the error cleanly.

**Comment by pronode** [comment]
In my case it was all about wrong Nodejs version. Update Nodejs to newest version, then run `npm i ipx`, `npm i` and you're done.

**Comment by andyslack** [comment]
Replacing `@nuxt/image-edge` with `@nuxt/image` also worked for me, remember to update your `nuxt.config.js` file's module config:

```
  modules: ['@nuxt/image'],
```
