### ISSUE TITLE
Cannot destructure property 'nuxt' of 'this' as it is undefined. 

### ISSUE THREAD

**Issue by fmabid** [nuxt/image#718]
Using "nuxt": "3.0.0". After adding Nuxt-image into `nuxt.config.ts` file and running the app, getting this error!!!
What's way out of this?

```
Cannot start nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined.                  21:21:31

  at imageModule2 (node_modules/@nuxt/image/dist/module.cjs:220:11)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
  ```

**Comment by w3bdesign** [comment]
Make sure you installed @nuxt/image-edge

**Comment by fmabid** [comment]
> Make sure you installed @nuxt/image-edge

Yeah, I did so. Thanks.  Initially, couldn't found about @nuxt/image-edge in the documentation.
