### ISSUE TITLE
Issue using nuxt-img in Nuxt 3

### ISSUE THREAD

**Issue by amireds** [nuxt/image#736]
Hi! After installing @nuxt/image in nuxt v3.0.0, I get the below error in my terminal

`annot start nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined.   17:43:34
  at imageModule2 (node_modules/@nuxt/image/dist/module.cjs:220:11)
  at installModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)`
  
  My package.json file:
  

  "devDependencies": {
    "@nuxt/image": "^0.7.1",
    "@nuxt/postcss8": "^1.1.3",
    "@volar-plugins/vetur": "latest",
    "autoprefixer": "^10.4.13",
    "nuxt": "3.0.0",
    "nuxt-icon": "^0.2.10",
    "nuxt-svgo": "^1.1.0",
    "postcss": "^8.4.20",
    "prettier": "^2.8.1",
    "tailwindcss": "^3.2.4"
  },
  "dependencies": {
    "@headlessui/vue": "^1.7.9",
    "@vuepic/vue-datepicker": "^3.6.5",
    "dayjs": "^1.11.7",
    "nuxt-icons": "^3.0.0"
  }

Please help, what am I doing wrong?

**Comment by danielroe** [comment]
You will need to install `@nuxt/image-edge` for Nuxt 3 support.
