### ISSUE TITLE
error : Cannot destructure property 'nuxt' of 'this' as it is undefined.

### ISSUE THREAD

**Issue by AmirAbbas-dev** [nuxt/image#770]
i install with **npm install -D @nuxt/image** and add to nuxt moduls but when run **npx nuxi dev** give me this error :

```
 ERROR  Cannot start nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                     12:34:15  

  at imageModule2 (node_modules\@nuxt\image\dist\module.cjs:220:11)
  at installModule (/A:/Programming/Project/CryptoCurrencyPrice-Fronend/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (/A:/Programming/Project/CryptoCurrencyPrice-Fronend/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/A:/Programming/Project/CryptoCurrencyPrice-Fronend/node_modules/nuxi/dist/chunks/dev.mjs:6781:9)
  at async Object.invoke (/A:/Programming/Project/CryptoCurrencyPrice-Fronend/node_modules/nuxi/dist/chunks/dev.mjs:6842:5)
  at async _main (/A:/Programming/Project/CryptoCurrencyPrice-Fronend/node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by danielroe** [comment]
If you are using Nuxt 3, you should use `@nuxt/image-edge` for now.

**Comment by jaybharadia** [comment]
> If you are using Nuxt 3, you should use `@nuxt/image-edge` for now.

Hi @danielroe , Should i mention this package name in documentation ? This will help developers in setup process.

**Comment by danielroe** [comment]
No, it is now in RC and it should be `@nuxt/image@rc` for now.

**Comment by Foddie2** [comment]
And for this case with the same error 

` ERROR  Cannot start nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                  10:56:35  

  at pwa (node_modules\@nuxtjs\pwa\dist\pwa.js:733:10)
  at installModule (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/@nuxt/kit/dist/index.mjs:2439:101)
  at async initNuxt (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/nuxt/dist/index.mjs:3702:7)
  at async NuxtDevServer._load (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/nuxi/dist/chunks/dev2.mjs:253:5)
  at async NuxtDevServer.load (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/nuxi/dist/chunks/dev2.mjs:185:7)
  at async NuxtDevServer.init (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/nuxi/dist/chunks/dev2.mjs:180:5)
  at async Object.run (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/nuxi/dist/chunks/dev-child.mjs:101:5)
  at async runCommand$1 (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (/C:/Users/Ben-Agala/Desktop/TechBytes-Today/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7)`

**Comment by danielroe** [comment]
@Foddie2 If you are experiencing this please open a new issue with a reproduction. (I'm almost certain you have the wrong module version installed.)

**Comment by JeremyMees** [comment]
I installed @nuxt/image-edge version `1.3.0-28427865.ae93934`. It automatically installs @nuxt/image version `0.7.2`.
When it's done installing it throws this error.

Using Nuxt 3.9.3
