### ISSUE TITLE
Tests fail when using nuxt-img

### ISSUE THREAD

**Issue by docmattman** [nuxt/image#814]
I'm hitting errors when testing after implementing nuxt/image.  All pages/components work and render properly, but tests fail. 
 Seeing this on all component tests that use `<nuxt-img>`:

```
TypeError: $img is not a function
 ❯ ReactiveEffect.fn node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.mjs:63:45
     62|         link: [{
     63|           rel: "preload",
     64|           as: "image",
       |                   ^
     65|           ...!isResponsive ? { href: src.value } : {
     66|             href: sizes.value.src,
 ❯ ReactiveEffect.run node_modules/@vue/reactivity/dist/reactivity.cjs.js:194:25
 ❯ ComputedRefImpl.get value [as value] node_modules/@vue/reactivity/dist/reactivity.cjs.js:1163:39
 ❯ ReactiveEffect.fn node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.mjs:65:102
 ❯ ReactiveEffect.run node_modules/@vue/reactivity/dist/reactivity.cjs.js:194:25
 ❯ ComputedRefImpl.get value [as value] node_modules/@vue/reactivity/dist/reactivity.cjs.js:1163:39
 ❯ Proxy.<anonymous> node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.mjs:101:16
 ❯ renderComponentRoot node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:906:44
 ❯ ReactiveEffect.componentUpdateFn [as fn] node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5587:57
 ❯ ReactiveEffect.run node_modules/@vue/reactivity/dist/reactivity.cjs.js:194:25
```

Any idea how I can solve this?

**Comment by danielroe** [comment]
I would suggest using https://github.com/danielroe/nuxt-vitest, which we are now using internally in nuxt/image to test it, and handles running your unit tests in a nuxt environment.

**Comment by docmattman** [comment]
I must have something setup incorrectly because I am using that for testing in the nuxt env.  The tests pass fine when I use a normal img tag, but when I replace it with nuxt-img it gives the errors above.

**Comment by danielroe** [comment]
Maybe you can share your code? Are you using `mountSuspended`?

**Comment by docmattman** [comment]
I'll try to setup a minimum reproduction of it if I can.  I'm guessing I must have something configured incorrectly though, since (possibly related) I've also been seen these errors on my local dev server when running nuxt-vitest:

```
✘ [ERROR] Could not resolve "#imports"

    node_modules/vitest-environment-nuxt/dist/utils.mjs:5:46:
      5 │ import { defineComponent, useRouter, h } from '#imports';
        ╵                                               ~~~~~~~~~~

  You can mark the path "#imports" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "#build/root-component.mjs"

    node_modules/vitest-environment-nuxt/dist/utils.mjs:6:21:
      6 │ import NuxtRoot from '#build/root-component.mjs';
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "#build/root-component.mjs" as external to exclude it from the bundle, which
  will remove this error.


 ERROR  error while updating dependencies:                                                                                2:35:13 AM
Error: Build failed with 2 errors:
node_modules/vitest-environment-nuxt/dist/utils.mjs:5:46: ERROR: Could not resolve "#imports"
node_modules/vitest-environment-nuxt/dist/utils.mjs:6:21: ERROR: Could not resolve "#build/root-component.mjs"
    at failureErrorWithLog (/home/mattman/projects/MoneyLineDAO/web/node_modules/esbuild/lib/main.js:1636:15)
    at /home/mattman/projects/MoneyLineDAO/web/node_modules/esbuild/lib/main.js:1048:25
    at /home/mattman/projects/MoneyLineDAO/web/node_modules/esbuild/lib/main.js:1512:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by danielroe** [comment]
The main thing is that I would confirm you're running those tests in the nuxt environment.

**Comment by docmattman** [comment]
Sorry, struggling a bit to get a minimum reproduction to share.  It's a bit of a bigger project and it's tedious to try to strip everything out to get it to the bare bones.  I do have `nuxt` set for the environment on my vitest.config.ts file though:

```
import { defineVitestConfig } from 'nuxt-vitest/config';

export default defineVitestConfig({
  test: {
    environment: 'nuxt',
    globals: true,
    globalSetup: './tests/globals.ts',

    coverage: {
      include: [
        'components/**/*',
        'composables/**/*',
        'layouts/**/*',
        'pages/**/*',
        'server/**/*',
        'store/**/*',
        'utils/**/*',
      ],
      exclude: ['**/*.spec.*', '**/constants.*', 'components/Icons/*'],
      reporter: ['text', 'json', 'html'],
      all: true,
      lines: 95,
      functions: 95,
      branches: 95,
      statements: 95,
    },
  },
});
```

**Comment by tomsdob** [comment]
Hi, I'm having the same issue, are there any updates?
