### ISSUE TITLE
Cannot start nuxt: Cannot destructure property 'nuxt' of 'this' as it is undefined

### ISSUE THREAD

**Issue by FloofyFlare** [nuxt/image#905]
Im running on nuxt version 3.6.1 and I ran into an error when I attempted to install the nuxt image module. I get a message that points me to the node_modules/@nuxt/image/dist/module.cjs:220:11 folder and the node_modules/@nuxt/kit/dist/index.mjs:2409:101 folder so it looks like the error has to do with one of those dependencies.

In my package.json dependencies I have "@nuxt/image": "^1.0.0-rc.1" in the devDependencies installations.

Full error below (after running yarn dev)

Cannot destructure property 'nuxt' of 'this' as it is undefined.

  at imageModule2 (/home/floofyflare/code/VueProjects/finals/node_modules/@nuxt/image/dist/module.cjs:220:11)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:2409:101)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3174:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3240:5)
  at async loadNuxt (/home/floofyflare/code/VueProjects/finals/node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)

error Command failed with exit code 1.

**Comment by danielroe** [comment]
I suspect you have the old version of the module installed rather than the rc. If not, would you provide a reproduction? 🙏

**Comment by FloofyFlare** [comment]
Thanks for the help here is a reproduction.
![Screenshot 2023-07-04 135434](https://github.com/nuxt/image/assets/85596143/f40b7336-0695-4d33-93e4-fc04b913767f)
![Screenshot 2023-07-04 135651](https://github.com/nuxt/image/assets/85596143/5344a5c1-befd-404b-b73c-265455ff5981)
![Screenshot 2023-07-04 135809](https://github.com/nuxt/image/assets/85596143/4dd57f3d-5f74-4b35-955f-e3bc50e9aa24)
![Screenshot 2023-07-04 135825](https://github.com/nuxt/image/assets/85596143/80485bf5-d82e-46c6-947e-db90b61654f1)

It worked in the reproduction it must have been an old version of the module I reinstalled all the packages I was using and it works well now.
