### ISSUE TITLE
Nuxt image error while displaying in child component

### ISSUE THREAD

**Issue by GunaDinesh** [nuxt/image#993]
I have an issue using dynamic image src in Nuxt3. 

I have images stored in /public/img folder, I have a child component called TeamMember which is called several time by parent component WhoWeAre. 

It is called like this: 
`<TeamMember color="orange" photo="imge_photo" name="member" post="Dev" grade="Senior" exp="2 years"></TeamMember>`

Inside TeamMember component, after retrieving props, I'm using this function to check the path: 
`const imagePath = computed(() => {
  return require(`../assets/img/${props.photo}.png`);
});`

And using `NuxtImg` like this: 
<NuxtImg :src="imagePath" class="rounded-full" :alt="name"/>

In my local env I'm getting this error: 
```
500
Invalid or unexpected token

at wrapSafe (node:internal/modules/cjs/loader:1178:20)
at Module._compile (node:internal/modules/cjs/loader:1220:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at require (node:internal/modules/cjs/helpers:110:18)
at ReactiveEffect.fn (...\components\TeamMember.js:30:14)
at ReactiveEffect.run (C:\armonik.fr\node_modules\.pnpm\@vue+reactivity@3.3.4\node_modules\@vue\reactivity\dist\reactivity.cjs.js:162:19)
```

I know the meaning of Invalid or Unexpected token but in that case I don't understand.

**Comment by urbgimtam** [comment]
Your images are in /public/img folder, but you are trying to retrieve them from `assets`.

Your code should be:
```
const imagePath = computed(() => { 
   return `/img/${props.photo}` 
});
 ```
 
Explanation: https://nuxt.com/docs/getting-started/assets

If you are not making any calculations in your TeamMember component, you can simply call `/img/${props.photo}` 
 as the src for your `<img>` or `<NuxtImg>`.
 
```<NuxtImg :src="`/img/${props.photo}`" />```

**Comment by GunaDinesh** [comment]
@urbgimtam, I made a mistake, I was indeed using the function like this: 

```
const imagePath = computed(() => {
  return require(`/img/${props.photo}.png`);
});
```

I want to keep the require method because there is a difference between my local and my GH Pages prod env, your solution works on local but not in prod.

**Comment by GunaDinesh** [comment]
Can anyone help me out with this issue ?
